# Server Configurations
server:
  port: 9020

# Spring Configurations
spring:
  application:
    name: parking-lot
  # Database Configurations
  datasource:
    url: ${PARKING_DATASOURCE_URL}
    username: ${PARKING_DB_USER}
    password: ${PARKING_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
